import os
import traceback

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel
from mitigation.city_infrastructure_network import mitigate

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["GET", "POST", "OPTIONS", "PUT", "DELETE"],
    allow_headers=["*"],
    expose_headers=["*"],
)


# Fallback OPTIONS handler in case middleware doesn't catch it
@app.options("/{rest_of_path:path}")
async def preflight_handler(request: Request, rest_of_path: str):
    return Response(
        status_code=200,
        headers={
            "Access-Control-Allow-Origin": "*",
            "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
            "Access-Control-Allow-Headers": "*",
        },
    )


@app.get("/health")
def health():
    """Quick health check so the frontend knows the backend is reachable."""
    analysis_exists = os.path.exists(
        os.path.join(os.path.dirname(__file__), "Data", "apocalypse_analysis.json")
    )
    return {
        "status": "ok",
        "analysis_ready": analysis_exists,
        "groq_configured": bool(os.environ.get("GROQ_API_KEY")),
    }


class CityRequest(BaseModel):
    city: str


@app.post("/run_pipeline")
def run_pipeline(req: CityRequest):
    try:
        from main import receive
        analysis = receive(req.city)
        return {"status": "ok", "analysis": analysis}
    except Exception as e:
        traceback.print_exc()
        return JSONResponse(
            status_code=500,
            content={"status": "error", "detail": f"{type(e).__name__}: {e}"},
        )


@app.post("/mitigate")
def mitigate_pipeline():
    """Run the mitigation module. Requires apocalypse_analysis.json to exist
    (generated by /run_pipeline)."""
    analysis_path = os.path.join(
        os.path.dirname(__file__), "Data", "apocalypse_analysis.json"
    )
    if not os.path.exists(analysis_path):
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "detail": (
                    "apocalypse_analysis.json not found. "
                    "Run the pipeline for a city first via POST /run_pipeline."
                ),
            },
        )
    try:
        return mitigate()
    except Exception as e:
        traceback.print_exc()
        return JSONResponse(
            status_code=500,
            content={"status": "error", "detail": f"{type(e).__name__}: {e}"},
        )